import React, { useState } from "react";
import Markdown from "react-markdown";
import { Message } from "../types";
import { AskGPTEmblem } from "./AskGPTIcon";
import {
  Copy,
  Check,
  Volume2,
  Square,
  ThumbsUp,
  ThumbsDown,
  Share2,
  RotateCw,
  User,
} from "lucide-react";

interface ChatMessageProps {
  message: Message;
  isSpeaking: boolean;
  onSpeak: (text: string, messageId: string) => void;
  onStopSpeaking: () => void;
  onRate?: (messageId: string, rating: "like" | "dislike" | null) => void;
  onRegenerate?: (messageId: string) => void;
  isLoading?: boolean;
}

export const ChatMessage: React.FC<ChatMessageProps> = ({
  message,
  isSpeaking,
  onSpeak,
  onStopSpeaking,
  onRate,
  onRegenerate,
  isLoading = false,
}) => {
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);
  const [rating, setRating] = useState<"like" | "dislike" | null>(message.rating || null);

  const isUser = message.role === "user";

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(message.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error("Failed to copy:", e);
    }
  };

  const handleLike = () => {
    const nextRating = rating === "like" ? null : "like";
    setRating(nextRating);
    onRate?.(message.id, nextRating);
  };

  const handleDislike = () => {
    const nextRating = rating === "dislike" ? null : "dislike";
    setRating(nextRating);
    onRate?.(message.id, nextRating);
  };

  const handleSpeechToggle = () => {
    if (isSpeaking) {
      onStopSpeaking();
    } else {
      onSpeak(message.content, message.id);
    }
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: "AskGPT Response",
          text: message.content,
        });
        setShared(true);
        setTimeout(() => setShared(false), 2000);
      } catch (err: any) {
        if (err?.name !== "AbortError") {
          // Fallback to clipboard
          copyShareFallback();
        }
      }
    } else {
      copyShareFallback();
    }
  };

  const copyShareFallback = async () => {
    try {
      await navigator.clipboard.writeText(
        `${message.content}\n\n— Generated by AskGPT (by Pushpraj Kumar)`
      );
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    } catch (e) {
      console.error("Failed to share:", e);
    }
  };

  if (isUser) {
    return (
      <div id={`message-${message.id}`} className="flex w-full justify-end">
        <div className="flex flex-col items-end max-w-[88%] sm:max-w-[78%]">
          {/* User attachment preview if present */}
          {message.attachment && (
            <div className="mb-2">
              {message.attachment.mimeType.startsWith("image/") ? (
                <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-xs max-w-xs dark:border-gray-800 dark:bg-gray-900">
                  <img
                    src={`data:${message.attachment.mimeType};base64,${message.attachment.data}`}
                    alt={message.attachment.name}
                    className="max-h-60 w-auto object-cover rounded-t-2xl"
                  />
                  <div className="px-3 py-1.5 text-[11px] text-gray-600 dark:text-gray-400 truncate">
                    {message.attachment.name}
                  </div>
                </div>
              ) : (
                <div className="inline-flex items-center gap-2 rounded-2xl border border-gray-200 bg-white px-3.5 py-2 text-xs text-gray-700 shadow-xs dark:border-gray-800 dark:bg-gray-900 dark:text-gray-300">
                  <span className="font-medium">{message.attachment.name}</span>
                </div>
              )}
            </div>
          )}

          {/* User Message Bubble */}
          <div className="rounded-3xl bg-gray-200/80 px-4 sm:px-5 py-2.5 sm:py-3 text-sm sm:text-[15px] leading-relaxed text-gray-900 shadow-xs dark:bg-gray-800 dark:text-gray-100">
            <div className="whitespace-pre-wrap font-normal leading-relaxed">{message.content}</div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div id={`message-${message.id}`} className="group relative flex w-full gap-3 sm:gap-4">
      {/* Avatar */}
      <div className="shrink-0 pt-0.5">
        <AskGPTEmblem size="md" />
      </div>

      {/* Content Area */}
      <div className="flex-1 overflow-hidden min-w-0">
        {/* Header info (Role label & Timestamp) */}
        <div className="mb-1 flex items-center gap-2">
          <span className="text-xs font-semibold text-gray-900 dark:text-gray-100">
            AskGPT
          </span>
          <span className="text-[11px] text-gray-400 dark:text-gray-500">
            {new Date(message.timestamp).toLocaleTimeString([], {
              hour: "2-digit",
              minute: "2-digit",
            })}
          </span>
        </div>

        {/* Message Text / Markdown */}
        <div className="text-sm sm:text-base leading-relaxed text-gray-800 dark:text-gray-200 break-words">
          <div className="prose prose-sm sm:prose-base dark:prose-invert max-w-none space-y-2 prose-p:leading-relaxed prose-pre:bg-gray-950 prose-pre:text-gray-100 prose-pre:border prose-pre:border-gray-800 prose-pre:rounded-xl">
            <Markdown
              components={{
                pre({ children }) {
                  return (
                    <div className="my-2.5 overflow-hidden rounded-xl border border-gray-200 bg-gray-950 text-gray-100 dark:border-gray-800 shadow-xs">
                      <pre className="overflow-x-auto p-3.5 text-xs font-mono leading-relaxed">{children}</pre>
                    </div>
                  );
                },
                code({ className, children, ...props }) {
                  return (
                    <code
                      className={`${className || ""} rounded-md px-1.5 py-0.5 font-mono text-xs bg-gray-100 text-indigo-600 dark:bg-gray-800/90 dark:text-indigo-300`}
                      {...props}
                    >
                      {children}
                    </code>
                  );
                },
                p({ children }) {
                  return <p className="mb-2 last:mb-0 leading-relaxed">{children}</p>;
                },
                ul({ children }) {
                  return <ul className="list-disc pl-5 mb-2 space-y-1">{children}</ul>;
                },
                ol({ children }) {
                  return <ol className="list-decimal pl-5 mb-2 space-y-1">{children}</ol>;
                },
                li({ children }) {
                  return <li className="mb-0.5 leading-relaxed">{children}</li>;
                },
                blockquote({ children }) {
                  return (
                    <blockquote className="border-l-3 border-indigo-500 pl-3 italic text-gray-600 dark:text-gray-400 my-2">
                      {children}
                    </blockquote>
                  );
                },
                a({ href, children }) {
                  return (
                    <a
                      href={href}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="font-medium text-indigo-600 underline underline-offset-2 hover:text-indigo-500 dark:text-indigo-400 dark:hover:text-indigo-300"
                    >
                      {children}
                    </a>
                  );
                },
              }}
            >
              {message.content}
            </Markdown>
          </div>
        </div>

        {/* Action Toolbar - STRICTLY FOR AI RESPONSES ONLY - Clean borderless */}
        <div className="mt-2.5 flex flex-wrap items-center gap-1 pt-1">
          {/* Copy Button */}
          <button
            type="button"
            onClick={handleCopy}
            className={`flex items-center gap-1.5 rounded-lg px-2 py-1 text-xs font-medium transition-colors ${
              copied
                ? "bg-emerald-50 text-emerald-600 dark:bg-emerald-950/40 dark:text-emerald-400"
                : "text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-200"
            }`}
            title={copied ? "Copied to clipboard" : "Copy response"}
            aria-label="Copy response"
          >
            {copied ? (
              <>
                <Check className="h-3.5 w-3.5 text-emerald-500" />
                <span className="text-[11px] text-emerald-600 dark:text-emerald-400">Copied</span>
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5" />
                <span className="text-[11px]">Copy</span>
              </>
            )}
          </button>

          {/* Like Button */}
          <button
            type="button"
            onClick={handleLike}
            className={`flex items-center gap-1 rounded-lg px-2 py-1 text-xs font-medium transition-colors ${
              rating === "like"
                ? "bg-emerald-50 text-emerald-600 dark:bg-emerald-950/50 dark:text-emerald-400"
                : "text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-200"
            }`}
            title={rating === "like" ? "Remove like" : "Good response"}
            aria-label="Like response"
          >
            <ThumbsUp
              className={`h-3.5 w-3.5 ${
                rating === "like" ? "fill-emerald-600 dark:fill-emerald-400" : ""
              }`}
            />
          </button>

          {/* Dislike Button */}
          <button
            type="button"
            onClick={handleDislike}
            className={`flex items-center gap-1 rounded-lg px-2 py-1 text-xs font-medium transition-colors ${
              rating === "dislike"
                ? "bg-rose-50 text-rose-600 dark:bg-rose-950/50 dark:text-rose-400"
                : "text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-200"
            }`}
            title={rating === "dislike" ? "Remove dislike" : "Poor response"}
            aria-label="Dislike response"
          >
            <ThumbsDown
              className={`h-3.5 w-3.5 ${
                rating === "dislike" ? "fill-rose-600 dark:fill-rose-400" : ""
              }`}
            />
          </button>

          {/* Read Aloud Button */}
          <button
            type="button"
            onClick={handleSpeechToggle}
            className={`flex items-center gap-1.5 rounded-lg px-2 py-1 text-xs font-medium transition-colors ${
              isSpeaking
                ? "bg-indigo-100 text-indigo-700 dark:bg-indigo-950/60 dark:text-indigo-300 animate-pulse"
                : "text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-200"
            }`}
            title={isSpeaking ? "Stop speech" : "Read aloud"}
            aria-label="Read aloud"
          >
            {isSpeaking ? (
              <>
                <Square className="h-3.5 w-3.5 fill-current" />
                <span className="text-[11px]">Stop</span>
              </>
            ) : (
              <>
                <Volume2 className="h-3.5 w-3.5" />
                <span className="text-[11px]">Read</span>
              </>
            )}
          </button>

          {/* Share Button */}
          <button
            type="button"
            onClick={handleShare}
            className={`flex items-center gap-1.5 rounded-lg px-2 py-1 text-xs font-medium transition-colors ${
              shared
                ? "bg-indigo-50 text-indigo-600 dark:bg-indigo-950/50 dark:text-indigo-400"
                : "text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-200"
            }`}
            title={shared ? "Shared successfully!" : "Share response"}
            aria-label="Share response"
          >
            {shared ? (
              <>
                <Check className="h-3.5 w-3.5 text-indigo-500" />
                <span className="text-[11px] text-indigo-600 dark:text-indigo-400">Shared</span>
              </>
            ) : (
              <>
                <Share2 className="h-3.5 w-3.5" />
                <span className="text-[11px]">Share</span>
              </>
            )}
          </button>

          {/* Regenerate Button */}
          {onRegenerate && (
            <button
              type="button"
              onClick={() => onRegenerate(message.id)}
              disabled={isLoading}
              className="flex items-center gap-1.5 rounded-lg px-2 py-1 text-xs font-medium text-gray-500 transition-colors hover:bg-gray-100 hover:text-gray-900 disabled:cursor-not-allowed disabled:opacity-50 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-200"
              title="Regenerate response"
              aria-label="Regenerate response"
            >
              <RotateCw className={`h-3.5 w-3.5 ${isLoading ? "animate-spin" : ""}`} />
              <span className="text-[11px]">Regenerate</span>
            </button>
          )}
        </div>
      </div>
    </div>
  );
};
